### ISSUE TITLE
kivymd_extensions.akivymd.uix.piechart

### ISSUE THREAD

**Issue by aybdee** [tjpin/Admin-Dashboard#1]
from kivymd_extensions.akivymd.uix.piechart import AKPieChart 

uix/piechart doesn't exist in the kivymd_extensions.akivymd repo

I checked Sep 21, 2021
did your code use an older version?

**Comment by lazarus-muya** [comment]
> from kivymd_extensions.akivymd.uix.piechart import AKPieChart
> 
> uix/piechart doesn't exist in the kivymd_extensions.akivymd repo
> 
> I checked Sep 21, 2021 did your code use an older version?

KivyMD is still under active development, so changes happen everyday.
Use  `pip install kivymd_extensions.akivymd`

**Comment by Kanfit** [comment]
Have the same error as above. I use latest kivy and just installed kivymd_extensions.akivymd.
