### ISSUE TITLE
No module named 'kivymd_extensions.akivymd.uix.piechart'

### ISSUE THREAD

**Issue by Kanfit** [tjpin/Admin-Dashboard#2]
There is previously closed issue with the same problem. Any soliton for that?
Solution wasn't provided yet.

**Comment by lazarus-muya** [comment]
`pip install kivymd_extensions.akivymd`.

Then ~ `from kivymd_extensions.akivymd.uix.charts import AkPieChart`

**Comment by Kanfit** [comment]
Thanks that worked for me.
Also property orientation:'vertical' must be deleted from "TableRecycleGridLayout:" in kivymd/uix/datatables.py
